version: '3'
services:


  nats-server:
    image: nats
      
  client-gateway:
    image: client-gateway-prod
    build:
      context: ./client-gateway
      dockerfile: Dockerfile.prod
    ports:
      - "${CLIENT_GATEWAY_PORT-3000}:3000"
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=nats://nats-server:4222

  orders-db:
    image: postgres:16.2
    environment:
      POSTGRES_USER: ${ORDER_USER_DB}
      POSTGRES_PASSWORD: ${ORDER_PASSWORD_DB}
      POSTGRES_DB: ${ORDER_DATABASE_NAME}
    ports:
      - '${ORDER_PORT_DB:-5433}:5432'
    volumes:
      - ./orders-ms/postgres:/var/lib/postgresql/data

  products-ms:
    image: products-ms-prod
    build:
      context: ./products-ms
      dockerfile: Dockerfile.prod
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db
      
  orders-ms:
    image: orders-ms-prod
    build:
      context: ./orders-ms
      dockerfile: Dockerfile.prod
      args:
        - ORDERS_MS_DATABASE_URL=${ORDERS_MS_DATABASE_URL}
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${ORDERS_MS_DATABASE_URL}

  payments-ms:
    image: payments-ms-prod
    build:
      context: ./payments-ms
      dockerfile: Dockerfile.prod
    ports:
      - '${PAYMENT_MS_PORT}:${PAYMENT_MS_PORT}'
    environment:
    - PAYMENT_MS_PORT=${PAYMENT_MS_PORT}
    - NATS_SERVERS=nats://nats-server:4222
    - DATABASE_URL=file:./dev.db
    - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
    - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
    - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
    - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}

  auth-ms:
    image: auth-ms-prod
    build:
      context: ./auth-ms
      dockerfile: Dockerfile.prod
    depends_on:
      - nats-server
    environment:
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}