version: '3'
services:

  # orders-db:
  #   image: postgres:16.2
  #   environment:
  #     POSTGRES_USER: ${ORDER_USER_DB}
  #     POSTGRES_PASSWORD: ${ORDER_PASSWORD_DB}
  #     POSTGRES_DB: ${ORDER_DATABASE_NAME}
  #   ports:
  #     - '${ORDER_PORT_DB:-5433}:5432'
  #   volumes:
  #     - ./orders-ms/postgres:/var/lib/postgresql/data

  nats-server:
    image: nats
    ports:
      - "4222:4222"
      - "8222:8222"
      
  client-gateway:
    image: client-gateway
    build:
      context: ./client-gateway
      dockerfile: Dockerfile
    ports:
      - "${CLIENT_GATEWAY_PORT-3000}:3000"
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222

  # products-ms:
  #   image: products-ms
  #   build:
  #     context: ./products-ms
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./products-ms/src:/usr/src/app/src
  #   command: npm run start:dev
  #   environment:
  #     - PORT=3000
  #     - NATS_SERVERS=nats://nats-server:4222
  #     - DATABASE_URL=file:./dev.db
      
  # orders-ms:
  #   image: orders-ms
  #   build:
  #     context: ./orders-ms
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3002:3002"
  #   depends_on:
  #     - orders-db
  #   volumes:
  #     - ./orders-ms/src:/usr/src/app/src
  #   command: npm run start:dev
  #   environment:
  #     - PORT=3002
  #     - NATS_SERVERS=nats://nats-server:4222
  #     - DATABASE_URL=postgresql://postgres:postgres@orders-db:5432/orders?schema=public

  # payments-ms:
  #   image: payments-ms
  #   build:
  #     context: ./payments-ms
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./payments-ms/src:/usr/src/app/src
  #   ports:
  #     - '${PAYMENT_MS_PORT}:${PAYMENT_MS_PORT}'
  #   command: npm run start:dev
  #   environment:
  #   - PAYMENT_MS_PORT=${PAYMENT_MS_PORT}
  #   - NATS_SERVERS=nats://nats-server:4222
  #   - DATABASE_URL=file:./dev.db
  #   - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
  #   - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
  #   - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
  #   - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}

  auth-ms:
    image: auth-ms
    build:
      context: ./auth-ms
      dockerfile: Dockerfile
    volumes:
      - ./auth-ms/src:/usr/src/app/src
    command: npm run start:dev
    depends_on:
      - nats-server
    environment:
      - NATS_SERVERS=nats://nats-server:4222