apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: payments-ms
  name: payments-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payments-ms
    spec:
      containers:
        - image: northamerica-northeast2-docker.pkg.dev/microservice-produc-back/image-registra/payments-ms-prod
          name: payments-ms-prod
          env:
            - name: NATS_SERVERS
              value: "nats://nats-service"

            - name: "PAYMENT_MS_PORT"
              valueFrom:
                secretKeyRef:
                  name: payments-secrets
                  key: PAYMENT_MS_PORT

            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: payments-secrets
                  key: STRIPE_SECRET_KEY

            - name: STRIPE_ENDPOINT_SECRET
              valueFrom:
                secretKeyRef:
                  name: payments-secrets
                  key: STRIPE_ENDPOINT_SECRET

            - name: STRIPE_SUCCESS_URL
              valueFrom:
                secretKeyRef:
                  name: payments-secrets
                  key: STRIPE_SUCCESS_URL

            - name: STRIPE_CANCEL_URL
              valueFrom:
                secretKeyRef:
                  name: payments-secrets
                  key: STRIPE_CANCEL_URL
          resources: {}
status: {}
